package persistence.entities;
// Generated 15 avr. 2021 à 15:20:58 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCategorie generated by hbm2java
 */
@Entity
@Table(name = "T_CATEGORIE", schema = "TPHIBERNATE")
public class TCategorie implements java.io.Serializable {

	private BigDecimal CIdcateg;
	private String CCodecateg;
	private String CLibellecateg;
	private Set<TProduit> TProduits = new HashSet<TProduit>(0);

	public TCategorie() {
	}

	public TCategorie(BigDecimal CIdcateg) {
		this.CIdcateg = CIdcateg;
	}

	public TCategorie(BigDecimal CIdcateg, String CCodecateg, String CLibellecateg, Set<TProduit> TProduits) {
		this.CIdcateg = CIdcateg;
		this.CCodecateg = CCodecateg;
		this.CLibellecateg = CLibellecateg;
		this.TProduits = TProduits;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "TCATEGORIE_SEQ", sequenceName = "TCATEGORIE_SEQ")
	@Column(name = "C_IDCATEG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCIdcateg() {
		return this.CIdcateg;
	}

	public void setCIdcateg(BigDecimal CIdcateg) {
		this.CIdcateg = CIdcateg;
	}

	@Column(name = "C_CODECATEG", length = 254)
	public String getCCodecateg() {
		return this.CCodecateg;
	}

	public void setCCodecateg(String CCodecateg) {
		this.CCodecateg = CCodecateg;
	}

	@Column(name = "C_LIBELLECATEG", length = 254)
	public String getCLibellecateg() {
		return this.CLibellecateg;
	}

	public void setCLibellecateg(String CLibellecateg) {
		this.CLibellecateg = CLibellecateg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCategorie")
	public Set<TProduit> getTProduits() {
		return this.TProduits;
	}

	public void setTProduits(Set<TProduit> TProduits) {
		this.TProduits = TProduits;
	}

}
