package persistence.entities;
// Generated 15 avr. 2021 à 15:20:58 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCommande generated by hbm2java
 */
@Entity
@Table(name = "T_COMMANDE", schema = "TPHIBERNATE")
public class TCommande implements java.io.Serializable {

	private BigDecimal CIdcommande;
	private TClient TClient;
	private TProduit TProduit;
	private BigDecimal CQtecommande;
	private Date CDatecommande;
	private BigDecimal CEtatcommande;

	public TCommande() {
	}

	public TCommande(BigDecimal CIdcommande, TClient TClient, TProduit TProduit) {
		this.CIdcommande = CIdcommande;
		this.TClient = TClient;
		this.TProduit = TProduit;
	}

	public TCommande(BigDecimal CIdcommande, TClient TClient, TProduit TProduit, BigDecimal CQtecommande,
			Date CDatecommande, BigDecimal CEtatcommande) {
		this.CIdcommande = CIdcommande;
		this.TClient = TClient;
		this.TProduit = TProduit;
		this.CQtecommande = CQtecommande;
		this.CDatecommande = CDatecommande;
		this.CEtatcommande = CEtatcommande;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "TCOMMANDE_SEQ", sequenceName = "TCOMMANDE_SEQ")
	@Column(name = "C_IDCOMMANDE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCIdcommande() {
		return this.CIdcommande;
	}

	public void setCIdcommande(BigDecimal CIdcommande) {
		this.CIdcommande = CIdcommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_IDCLIENT", nullable = false)
	public TClient getTClient() {
		return this.TClient;
	}

	public void setTClient(TClient TClient) {
		this.TClient = TClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_IDPRODUIT", nullable = false)
	public TProduit getTProduit() {
		return this.TProduit;
	}

	public void setTProduit(TProduit TProduit) {
		this.TProduit = TProduit;
	}

	@Column(name = "C_QTECOMMANDE", precision = 22, scale = 0)
	public BigDecimal getCQtecommande() {
		return this.CQtecommande;
	}

	public void setCQtecommande(BigDecimal CQtecommande) {
		this.CQtecommande = CQtecommande;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "C_DATECOMMANDE", length = 7)
	public Date getCDatecommande() {
		return this.CDatecommande;
	}

	public void setCDatecommande(Date CDatecommande) {
		this.CDatecommande = CDatecommande;
	}

	@Column(name = "C_ETATCOMMANDE", precision = 22, scale = 0)
	public BigDecimal getCEtatcommande() {
		return this.CEtatcommande;
	}

	public void setCEtatcommande(BigDecimal CEtatcommande) {
		this.CEtatcommande = CEtatcommande;
	}

}
