package persistence.entities;
// Generated 15 avr. 2021 à 15:20:58 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TStockuser generated by hbm2java
 */
@Entity
@Table(name = "T_STOCKUSER", schema = "TPHIBERNATE")
public class TStockuser implements java.io.Serializable {

	private BigDecimal SIduser;
	private String SUsername;
	private String SPassword;
	private String SRole;

	public TStockuser() {
	}

	public TStockuser(BigDecimal SIduser) {
		this.SIduser = SIduser;
	}

	public TStockuser(BigDecimal SIduser, String SUsername, String SPassword, String SRole) {
		this.SIduser = SIduser;
		this.SUsername = SUsername;
		this.SPassword = SPassword;
		this.SRole = SRole;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "TSTOCKUSER_SEQ", sequenceName = "TSTOCKUSER_SEQ")
	@Column(name = "S_IDUSER", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSIduser() {
		return this.SIduser;
	}

	public void setSIduser(BigDecimal SIduser) {
		this.SIduser = SIduser;
	}

	@Column(name = "S_USERNAME", length = 20)
	public String getSUsername() {
		return this.SUsername;
	}

	public void setSUsername(String SUsername) {
		this.SUsername = SUsername;
	}

	@Column(name = "S_PASSWORD", length = 20)
	public String getSPassword() {
		return this.SPassword;
	}

	public void setSPassword(String SPassword) {
		this.SPassword = SPassword;
	}

	@Column(name = "S_ROLE", length = 20)
	public String getSRole() {
		return this.SRole;
	}

	public void setSRole(String SRole) {
		this.SRole = SRole;
	}

}
